services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: 1.27.4
    image: nginx-brotli:slim
    container_name: nginx-brotli
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
